apiVersion: apps/v1
kind: Deployment
metadata:
  name: <nombre>
  namespace: <namespace>
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: <nombre>
  template:
    metadata:
      labels:
        app: <nombre>
    spec:
      containers:
        - name: angular-app
          image: <url imagen>:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: <nombre>
  namespace: <namespace>
  labels:
    app: <nombre>
spec:
  selector:
    app: <nombre>
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: <nombre>
  namespace: <namespace>
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: <namespace>.inphotech.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: <nombre>
                port:
                  number: 80
