apiVersion: apps/v1
kind: Deployment
metadata:
  name: organizapp-frontend
  namespace: grupo14
  labels:
    app: angular-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: organizapp-frontend
  template:
    metadata:
      labels:
        app: organizapp-frontend
    spec:
      containers:
        - name: angular-app
          image: ghcr.io/optimizapp/proyecto_organizapp_front:latest
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: ghcr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: organizapp-frontend
  namespace: grupo14
  labels:
    app: organizapp-frontend
spec:
  selector:
    app: organizapp-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: organizapp-frontend
  namespace: grupo14
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: grupo14.inphotech.co
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: organizapp-frontend
                port:
                  number: 80
