name: Deploy Angular Docker Image

on:
  workflow_dispatch:

env:
  IMAGE_NAME: <url imagen>

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t ${{ env.IMAGE_NAME }}:latest .

      - name: Login to image registry
        if: ${{ false }}
        run: echo "<token o secreto GitHub Actions>" | docker login "<registry>" -u "<usuario o secreto GitHub Actions>" --password-stdin

      - name: Push Docker image
        if: ${{ false }}
        run: docker push ${{ env.IMAGE_NAME }}:latest
